export const fotos = [
    {url: "churrasqueira.jpeg", alt: "Area Externa"},
    {url: "exterior2.jpeg", alt: "Area Externa"},
    {url: "exterior3.jpeg", alt: "Area Externa"},
    {url: "guardasol.jpeg", alt: "Area Externa"},
    {url: "piscina-cima.jpeg", alt: "Area Externa"},
    {url: "piscina-frente-antiga.jpg", alt: "Area Externa"},
    {url: "piscina-frente.jpeg", alt: "Area Externa"},
    {url: "piscina-fundo.jpeg", alt: "Area Externa"},
    {url: "piscina-noite.jpg", alt: "Area Externa"},
    {url: "quarto.jpeg", alt: "Quarto"},
    {url: "hall.jpeg", alt: "Hall"},
    {url: "bar.jpeg", alt: "Salao Externo"},
    {url: "salao-dentro.jpeg", alt: "Salao Externo"},
    {url: "salao-exterior-geral.jpeg", alt: "Salao Externo"},
    {url: "salao-interno-aberto.jpg", alt: "Salao Interno"},
    {url: "salao-interno.jpeg", alt: "Salao Interno"},
    {url: "sinuca.jpeg", alt: "Salao Interno"},
    {url: "sinuca2.jpeg", alt: "Salao Interno"},
    {url: "tresguardasol.jpeg", alt: "Area Externa"},
    {url: "varanda.jpeg", alt: "Area Externa"},
] 